// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVNdPBICftuHSUkjkS0Vf_lBUGiblMIYE',
    appId: '1:294486967054:web:df7e9494ea55c9c3054d5f',
    messagingSenderId: '294486967054',
    projectId: 'chat-app-438c9',
    authDomain: 'chat-app-438c9.firebaseapp.com',
    storageBucket: 'chat-app-438c9.firebasestorage.app',
    measurementId: 'G-6SLP57EW3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTorNBGhhZFrrdk38dHwq_WG7IXOVLnnk',
    appId: '1:294486967054:android:6ea6125502e8eb6e054d5f',
    messagingSenderId: '294486967054',
    projectId: 'chat-app-438c9',
    storageBucket: 'chat-app-438c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7eo2VYlKOyD93h3p3owJD_qMahkyTWbc',
    appId: '1:294486967054:ios:c45ba175a29ee71e054d5f',
    messagingSenderId: '294486967054',
    projectId: 'chat-app-438c9',
    storageBucket: 'chat-app-438c9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
